name: jcmdc_proy_abril  # Nombre del entorno
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13.2
  - pandas=2.2.3
  - numpy=2.2.4
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - plotly=5.24.1
  - scikit-learn
  - pip
  - pip:
      - mysql-connector-python==9.2.0  # Instalación a través de pip
      - webdriver-manager==4.0.2
      - selenium==4.24.0
      - jsonschema==4.23.0
      - fastjsonschema==2.21.1
      - jupyter
      - ipykernel
      - ipython
      - notebook


